const fs = require('fs');
const path = require('path');

const mockRoot = path.join(__dirname, 'mock_exo');
const xmlDir = path.join(mockRoot, 'xml');
const gameDir = path.join(mockRoot, 'eXo', 'eXoDOS', '!dos', 'TestGame');
const imagesDir = path.join(mockRoot, 'Images', 'MS-DOS', 'Box - Front');

// Create directories
[xmlDir, gameDir, imagesDir].forEach(dir => {
    fs.mkdirSync(dir, { recursive: true });
});

// Create MS-DOS.xml
const xmlContent = `<?xml version="1.0" standalone="yes"?>
<LaunchBox>
  <Game>
    <Title>Test Game</Title>
    <Developer>Test Developer</Developer>
    <Publisher>Test Publisher</Publisher>
    <ReleaseDate>1990-01-01T00:00:00-00:00</ReleaseDate>
    <Genre>Action</Genre>
    <Series>Test Series</Series>
    <Notes>This is a test game generated by the launcher.</Notes>
    <ApplicationPath>eXo\\Games\\TestGame\\game.bat</ApplicationPath>
    <CoverImagePath>Images\\MS-DOS\\Box - Front\\Test Game-01.png</CoverImagePath>
  </Game>
</LaunchBox>`;

fs.writeFileSync(path.join(xmlDir, 'MS-DOS.xml'), xmlContent);

// Create dosbox.conf
const confContent = `[sdl]
fullscreen=false
fulldouble=false
fullresolution=original
windowresolution=original
output=overlay
autolock=true
sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper-0.74.map
usescancodes=true

[dosbox]
language=
machine=svga_s3
captures=capture
memsize=16

[render]
frameskip=0
aspect=false
scaler=normal2x

[cpu]
core=auto
cputype=auto
cycles=auto
cycleup=10
cycledown=20

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[midi]
mpu401=intelligent
mididevice=default
midiconfig=

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=44100

[gus]
gus=false
gusrate=44100
gusbase=240
irq1=5
irq2=5
dma1=3
dma2=3
ultradir=C:\\ULTRASND

[speaker]
pcspeaker=true
pcrate=44100
tandy=auto
tandyrate=44100
disney=true

[joystick]
joysticktype=auto
timed=true
autofire=false
swap34=false
buttonwrap=false

[serial]
serial1=dummy
serial2=dummy
serial3=disabled
serial4=disabled

[dos]
xms=true
ems=true
umb=true
keyboardlayout=auto

[ipx]
ipx=false

[autoexec]
@echo off
mount c .
c:
cls
echo This is a test game running in Emularity!
ver
pause
exit`;

fs.writeFileSync(path.join(gameDir, 'dosbox.conf'), confContent);

// Create dosbox.bat
// Note: The launcher looks for the start command in the bat file. 
// But for Emularity, we usually just want to run the executable.
// Let's make a simple bat that just runs "ver"
fs.writeFileSync(path.join(gameDir, 'dosbox.bat'), 'ver');

// Create dummy image
// We'll just create a 1x1 transparent PNG
const pngData = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64');
fs.writeFileSync(path.join(imagesDir, 'Test Game-01.png'), pngData);

console.log('Mock eXoDOS data created at:', mockRoot);
